# Generated by Django 6.0.1 on 2026-02-17 10:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absencereason',
            options={'ordering': ['order'], 'verbose_name': 'Причина пропуску', 'verbose_name_plural': 'Причини пропусків'},
        ),
        migrations.AlterModelOptions(
            name='evaluationtype',
            options={'ordering': ['order'], 'verbose_name': 'Тип оцінювання', 'verbose_name_plural': 'Типи оцінювання'},
        ),
        migrations.AddField(
            model_name='absencereason',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Колір (hex)'),
        ),
        migrations.AddField(
            model_name='absencereason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absencereason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='absencereason',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AddField(
            model_name='absencereason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='buildingaccesslog',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID турнікету'),
        ),
        migrations.AddField(
            model_name='buildingaccesslog',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Валідний доступ'),
        ),
        migrations.AddField(
            model_name='buildingaccesslog',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місце (вхід)'),
        ),
        migrations.AddField(
            model_name='buildingaccesslog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Обладнання'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Поверх'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('lecture', 'Лекційна'), ('computer', "Комп'ютерна"), ('lab', 'Лабораторна'), ('other', 'Інша')], default='other', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='graderule',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Колір (hex)'),
        ),
        migrations.AddField(
            model_name='graderule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graderule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис критеріїв'),
        ),
        migrations.AddField(
            model_name='graderule',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Максимальний бал'),
        ),
        migrations.AddField(
            model_name='graderule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='За замовчуванням'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина скасування'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, verbose_name='Домашнє завдання'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Скасований'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True, verbose_name='Матеріали (посилання)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки викладача'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='week_type',
            field=models.CharField(blank=True, choices=[('numerator', 'Чисельник'), ('denominator', 'Знаменник')], max_length=20, verbose_name='Тип тижня'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час виставлення оцінки'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_performances', to=settings.AUTH_USER_MODEL, verbose_name='Оцінено ким'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Бонусні бали'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версія запису'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік випуску'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Спеціальність'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='year_of_entry',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік вступу'),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код предмету'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кредити ECTS'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_lectures',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Годин лекцій'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_practicals',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Годин практичних'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всього годин'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, verbose_name='Навчальний рік'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активне'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 семестр'), (2, '2 семестр')], null=True, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото профілю'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ студентського квитка'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
