# Generated by Django 6.0 on 2026-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_news_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Світла'), ('dark', 'Темна')], default='light', max_length=5, verbose_name='Тема інтерфейсу'),
        ),
    ]
