# Generated by Django 6.0 on 2026-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_notification_advanced"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="MyBosco", max_length=200, verbose_name="Назва закладу"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=300, verbose_name="Слоган"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institution/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institution/",
                        verbose_name="Фавікон",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
            ],
            options={
                "verbose_name": "Налаштування закладу",
                "verbose_name_plural": "Налаштування закладу",
                "db_table": "institution_settings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="homeworksubmission",
            name="unique_homework_submission",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="max_points",
            field=models.PositiveIntegerField(default=12, verbose_name="Макс. балів"),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="duration_minutes",
            field=models.IntegerField(default=50, verbose_name="Тривалість (хв)"),
        ),
        migrations.AlterUniqueTogether(
            name="homeworksubmission",
            unique_together={("lesson", "student")},
        ),
    ]
