# Generated by Django 6.0 on 2026-04-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_institution_settings"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="homeworksubmission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="student",
        ),
        migrations.RemoveField(
            model_name="privatecomment",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="privatecomment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="evaluationtype",
            name="is_homework_type",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="homework",
        ),
        migrations.DeleteModel(
            name="SubmissionAttachment",
        ),
        migrations.DeleteModel(
            name="HomeworkSubmission",
        ),
        migrations.DeleteModel(
            name="PrivateComment",
        ),
    ]
