# Generated by Django 6.0 on 2026-04-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_homeworksubmission_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="notes",
        ),
        migrations.AddField(
            model_name="user",
            name="rfid_uid",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="RFID UID картки",
            ),
        ),
        migrations.DeleteModel(
            name="LessonAttachment",
        ),
    ]
