# Generated by Django 6.0 on 2026-04-30 (amended for safe data migration)

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_specialties_forward(apps, schema_editor):
    """Convert existing text specialty values into Specialty FK records."""
    StudyGroup = apps.get_model("main", "StudyGroup")
    Specialty = apps.get_model("main", "Specialty")

    seen = {}
    for group in StudyGroup.objects.all():
        text = (group.specialty_text or "").strip()
        if not text:
            continue
        if text not in seen:
            spec, _ = Specialty.objects.get_or_create(name=text)
            seen[text] = spec
        group.specialty_new = seen[text]
        group.save(update_fields=["specialty_new"])


def migrate_specialties_backward(apps, schema_editor):
    """Convert Specialty FK back to text field."""
    StudyGroup = apps.get_model("main", "StudyGroup")
    for group in StudyGroup.objects.select_related("specialty_new"):
        if group.specialty_new:
            group.specialty_text = group.specialty_new.name
            group.save(update_fields=["specialty_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_add_rfid_uid_to_user"),
    ]

    operations = [
        # 1. Create Specialty table
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Назва спеціальності"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Код спеціальності"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
            ],
            options={
                "verbose_name": "Спеціальність",
                "verbose_name_plural": "Спеціальності",
                "db_table": "specialties",
                "ordering": ["code", "name"],
            },
        ),
        # 2. Rename old text column to specialty_text to preserve data
        migrations.RenameField(
            model_name="studygroup",
            old_name="specialty",
            new_name="specialty_text",
        ),
        # 3. Add new FK column (nullable) named specialty_new
        migrations.AddField(
            model_name="studygroup",
            name="specialty_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="main.specialty",
                verbose_name="Спеціальність",
            ),
        ),
        # 4. Data migration: populate FK from old text values
        migrations.RunPython(
            migrate_specialties_forward,
            migrate_specialties_backward,
        ),
        # 5. Remove old text column
        migrations.RemoveField(
            model_name="studygroup",
            name="specialty_text",
        ),
        # 6. Rename FK column to 'specialty'
        migrations.RenameField(
            model_name="studygroup",
            old_name="specialty_new",
            new_name="specialty",
        ),
        # 7. Add db_index to course field
        migrations.AlterField(
            model_name="studygroup",
            name="course",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Курс",
            ),
        ),
    ]
